# Generated by Django 3.2.6 on 2021-11-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_user_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='MyClub',
        ),
    ]
