# Generated by Django 3.2.6 on 2021-11-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_myuser_myclub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyClub',
            new_name='MyClubUser',
        ),
        migrations.RemoveField(
            model_name='event',
            name='amanager',
        ),
        migrations.AlterField(
            model_name='venue',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Contact Phone'),
        ),
    ]
