# Generated by Django 3.2.6 on 2021-11-29 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20211128_2049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyClubUser',
            new_name='User',
        ),
    ]
