# Generated by Django 3.2.6 on 2021-12-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20211129_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='message',
            field=models.TextField(blank=True, verbose_name='Your Message'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='subject',
            field=models.TextField(default=1, verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
